	    | Project                         | position               | Status              | Assigned               | Candidates         | Billing type      | FTE  | Start Date | End Date   | Marker          | Interview | Account         |
		| ACSA                            | QA test                | Opportunity         | <null>                 | <null>             | Internal Project  | 0.95 | 21.09.2021 | 31.10.2021 | None            | no        | Kanda           |
		| Common Opportunities            | Python & R Developer   | Open                | <null>                 | No candidates      | Billable          | 1    | 21.06.2021 | 31.12.2021 | Overdue         | no        | Kanda           |
		| Staffing                        | Junior QA Manual       | Proposed candidates | <null>                 | Alexander Kashirin | Internal Projects | 1    | 29.07.2021 | 31.10.2021 | Overdue         | no        | Quantori        |
		| Engineering Competence Centeres | .NET Competence Head   | Active              | Alexander Tikhanovskiy | <null>             | Non-billable      | 0.25 | 28.05.2020 | 31.12.2021 | Other           | no        | Quantori        |
		| PoC parsing solution            | Assistant              | Finished            | Mark Fomin             | <null>             | Internal Projects | 1    | 01.11.2020 | 31.01.2021 | Other           | no        | J&J             |
		| MVP iParser                     | UX/UI specialist       | Active              | Artem Ivanov           | <null>             | Temporary         | 0.4  | 01.02.2021 | 30.09.2021 | Other           | no        | J&J             |
		| Broad Institute                 | QA Automation Engineer | Active              | Sergey Ruzin           | Davit Gelashvili   | Non-billable      | 0.5  | 26.10.2020 | 31.12.2021 | Rotation case   | no        | Broad Institute |
		| Aaa.test.change                 | starting soon test     | Open                | <null>                 | No candidates      | Billable          | 1    | 01.09.2021 | 14.01.2022 | Revenue leakage | Interview | Quantori        |
		| Sanofi                          | Lead Java/PySpark      | Cancelled           | <null>                 | <null>             | Billable          | 1    | 01.11.2019 | 31.10.2020 | Other           | no        | Sanofi          |
