$('.igem_content_wrapper').contents().unwrap();
$('.igem_column_wrapper').children("p.second").unwrap();
$('.igem_column_wrapper').children("p.first").remove()
$('.igem_column_wrapper').contents().unwrap();
$('#content').contents().unwrap();
$('#bodyContent').contents().unwrap();
$('#mw-content-text').contents().unwrap();
$('#globalWrapper').contents().unwrap();
$('#HQ_page').contents().unwrap();